config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :technologies
  resources :teams do
    member do
      get :assign_project
      post :assigned_project
      get :assign_member
      post :assigned_member
      get :assign_member_project
      post :assigned_member_project
      post :assigned_member_project_task
      get '/user/:user_id' => 'teams#users_details', as: :users_details
    end
  end
  resources :projects do
       resources :tasks do
            resources :dependencies
       end
  end
devise_for :users
root to: "home#dashboard"
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :project, optional: true
  has_many :dependencies 
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_project, only: [:index, :show, :new, :edit, :create, :update, :destroy]


  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = @project.tasks
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    #@task = Task.new(task_params)
     @task = @project.tasks.create(task_params)
     redirect_to project_tasks_path, notice: 'Task was successfully created.' 
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    @task.update(task_params)
    redirect_to project_tasks_path, notice: 'Task was successfully updated.'
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    redirect_to project_path(@project), notice: 'Task was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: [ @project, @project.tasks.build ], local: true) do |form| %>

  <div class="form-group">
    <%#= form.label :Add_task %>
    <%= form.text_field :name, id: :task_name,  class: "form-control", id: "exampleInputEmail1", aria_describedby: "emailHelp", placeholder: "Enter Task Details " %>
  </div>

  <div class="actions">
    <%= form.submit 'Save Task', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<strong>Task:</strong>
<%= task.name %>
<%= link_to 'Edit Task', edit_project_task_path(@project,task) %>
<%= link_to 'Destroy Task', project_task_path(@project,task),  method: :delete, data: { confirm: 'Are you sure?' } %>
<%= render 'dependencies/dependency', task: task %>      

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%#= form_with(model: task, local: true) do |form| %>
<%= form_with(model: [ @project, @task ], local: true) do |form| %>

  <div class="field">
    <%= form.label :edit_task %>
    <%= form.text_field :name, id: :task_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/index.html.erb
<strong>Project Name:- <%=@project.name %> <i>Tasks</i></strong>


<table>
  <thead>
    <tr>
      <th>Task Name</th>
      <th>Action</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= link_to 'Show', project_task_path(task.project, task) %></td>
        <td><%= link_to 'Edit', edit_project_task_path(task.project, task) %></td>
        <td><%= link_to ' Add Dependencies', project_task_dependencies_path(task.project, task) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Task', new_project_task_path %> |
<%= link_to "Back to Projects", projects_path %>

app/views/tasks/new.html.erb
<strong>Add Task to <i><%=@project.name %></i></strong>
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<p>
  <strong>Task:</strong>
  <%= @task.name %>
</p>
<%if @task.dependencies.first.present? %>
    <p>
     <strong>Dependencies:</strong>
    </p>
	<% @task.dependencies.each do |dependency| %>
     <p>
     <%= dependency.name%>
    </p>
	<%end%>
<%end%>

<% if ApplicationAuthorizer.creatable_by?(current_user) %>
  <%= link_to 'Edit', edit_project_task_path(@task.project, @task) %> |
  <%= link_to 'Back', project_tasks_path(@task.project) %>
<% end %>