config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :technologies
  resources :teams do
    member do
      get :assign_project
      post :assigned_project
      get :assign_member
      post :assigned_member
      get :assign_member_project
      post :assigned_member_project
      post :assigned_member_project_task
      get '/user/:user_id' => 'teams#users_details', as: :users_details
    end
  end
  resources :projects do
       resources :tasks do
            resources :dependencies
       end
  end
devise_for :users
root to: "home#dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/dependency.rb
class Dependency < ApplicationRecord
	belongs_to :task, optional: true
end

app/models/member_task.rb
class MemberTask < ApplicationRecord
	def self.member_tasks(team_id, user_id, project_id)
		 @tasks = []	
		  member_tasks = self.where(team_id: team_id, user_id: user_id, project_id: project_id)
		  member_tasks.each do |task|
	        task =Task.find(task.task_id)
	        @tasks.push(task)
		  end 
		  return @tasks
		end

		def self.assigned_task(user_id, project_id)
			self.where(team_id: User.find(user_id).team.id,  user_id: user_id, project_id: project_id)
		end

		def self.un_assigned_task(project)
			@un_assigned_task = []
        project.tasks.each do |t|
            unless self.where(task_id: t.id).first.present?
              @un_assigned_task.push(t)
            end
        end
       return @un_assigned_task
		end

end

app/models/project.rb
class Project < ApplicationRecord
	mount_uploader :document, DocumentUploader
    has_many :tasks
    has_many :project_teams
    has_many :teams, through: :project_teams
    has_many :user_projects
    has_many :users, through: :user_projects 
end

app/models/project_team.rb
class ProjectTeam < ApplicationRecord
	 belongs_to :project
     belongs_to :team
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :project, optional: true
  has_many :dependencies 
end

app/models/team.rb
class Team < ApplicationRecord
	 has_many :users
	 has_many :project_teams
     has_many :projects, through: :project_teams
end

app/models/technology.rb
class Technology < ApplicationRecord
	include Authority::Abilities
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  include Authority::UserAbilities
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :team, optional: true  
  has_many :user_projects
  has_many :projects, through: :user_projects


  after_create :assign_default_role

  def assign_default_role
    self.add_role(:newuser) if self.roles.blank?
  end
end

app/models/user_project.rb
class UserProject < ApplicationRecord
	 belongs_to :user
   belongs_to :project

   def self.is_already_assingned?(user_id, project_id)
   	 self.where(user_id: user_id, project_id: project_id).first.present?
   end

end

app/controllers/dependencies_controller.rb
class DependenciesController < ApplicationController
  before_action :set_dependency, only: [:show, :edit, :update, :destroy]
  before_action :set_project_and_task, only: [:index, :show, :new, :edit, :create, :update, :destroy]


 
  # GET /dependencies
  # GET /dependencies.json
  def index
    @dependencies = @task.dependencies
  end

  # GET /dependencies/1
  # GET /dependencies/1.json
  def show
  end

  # GET /dependencies/new
  def new
    @dependency = Dependency.new
  end

  # GET /dependencies/1/edit
  def edit
  end

  # POST /dependencies
  # POST /dependencies.json
  def create
    #@dependency = Dependency.new(dependency_params)
    @dependency = @task.dependencies.create(dependency_params)
    redirect_to project_task_dependencies_path(@project, @task), notice: 'Dependency was successfully created.'
       
  end

  # PATCH/PUT /dependencies/1
  # PATCH/PUT /dependencies/1.json
  def update
      @dependency.update(dependency_params)
      redirect_to project_task_dependencies_path(@project, @task), notice: 'Dependency was successfully updated.' 
     
  end

  # DELETE /dependencies/1
  # DELETE /dependencies/1.json
  def destroy
    @dependency.destroy
    redirect_to project_task_dependencies_path(@project, @task), notice: 'Dependency was successfully destroyed.' 
      
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dependency
      @dependency = Dependency.find(params[:id])
    end

  def set_project_and_task
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:task_id])
  end


    # Never trust parameters from the scary internet, only allow the white list through.
    def dependency_params
      params.require(:dependency).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def dashboard
		
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_project, only: [:index, :show, :new, :edit, :create, :update, :destroy]


  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = @project.tasks
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    #@task = Task.new(task_params)
     @task = @project.tasks.create(task_params)
     redirect_to project_tasks_path, notice: 'Task was successfully created.' 
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    @task.update(task_params)
    redirect_to project_tasks_path, notice: 'Task was successfully updated.'
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    redirect_to project_path(@project), notice: 'Task was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dependencies_helper.rb
module DependenciesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/views/dependencies/_dependency.html.erb
<% if task.dependencies.first.present? %>
	<% task.dependencies.each do |dependency| %>
		<p>
		<strong>Dependency:</strong>
		<%= dependency.name%>
		<%= link_to 'Edit Dependency', edit_project_task_dependency_path(@project,task, dependency)%>
		<%= link_to 'Destroy Dependency', project_task_dependency_path(@project,task, dependency),  method: :delete, data: { confirm: 'Are you sure?' } %>
		</p>
	<% end %>
<% end %>

app/views/dependencies/_form.html.erb
<%= form_with(model: [ @project, @task, @task.dependencies.build ], local: true) do |form| %>
  
  <div class="form-group">
    <%= form.label :Add_dependency %>
    <%= form.text_field :name, id: :dependency_name, class: "form-control", id: "exampleInputEmail1", aria_describedby: "emailHelp", placeholder: "Enter Dependency" %>
  </div>

  <div class="actions">
    <%= form.submit "Save Dependency", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/dependencies/edit.html.erb
<h1>Editing Dependency</h1>

<%= form_with(model: [ @project, @task, @dependency ], local: true) do |form| %>

  <div class="field">
    <%= form.label :Edit_dependency %>
    <%= form.text_field :name, id: :dependency_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dependencies/index.html.erb
<h1>Dependencies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dependencies.each do |dependency| %>
      <tr>
        <td><%= dependency.name %></td>
        <td><%= link_to 'Show', project_task_dependency_path(@project, @task, dependency) %></td>
        <td><%= link_to 'Edit', edit_project_task_dependency_path(@project, @task, dependency) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dependency', new_project_task_dependency_path(@project, @task) %> | 


<%= link_to 'Back to Tasks', project_tasks_path(@project) %>| 


<%= link_to 'Back to prtojects',projects_path %>

app/views/dependencies/new.html.erb
<h1>New Dependency</h1>

<%= render 'form', dependency: @dependency %>

<%= link_to 'Back', project_task_dependencies_path(@project, @task) %>

app/views/dependencies/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @dependency.name %>
</p>

<%= link_to 'Edit', edit_project_task_dependency_path(@project, @task, @dependency) %> |
<%= link_to 'Back to dependency ', project_task_dependencies_path(@project, @task) %>